server:
  port: 9001
eureka:
  server:
    eviction-interval-timer-in-ms: 10000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
        defaultZone: http://admin:123456@127.0.0.1:9001/eureka
#        defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
  instance: # eureak实例定义
    hostname: eureka1 # 定义 Eureka 实例所在的主机名称
  
logging:
  level:
    com.xiongyc.product: DEBUG #INFO
    
spring:
  security:
    user:
      name: admin
      password: 123456    
 