server:
  port: 8080 

mybatis:
 mapper-locations: # 所有的mapper映射文件
 - classpath:mapping/*.xml 
  
spring:
  application:
    name: product-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # 配置MySQL的驱动程序类
    url: jdbc:mysql://120.79.207.20:3306/fsylitcps?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT%2B8 # 数据库连接地址
    username: erp # 数据库用户名
    password: erp@fsfdad # 数据库连接密码    
  redis: 
    port: 6379
    host: 47.107.158.20
    password: edo9567
  
logging:
  level:
    com.xiongyc: debug
 