server:
  port: 8080
  servlet:
    context-path: /weChat
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
mybatis:
  type-aliases-package: com.xiongyc.product.bean
  mapper-locations:
  - classpath:mapper/*.xml
api:
  swagger:
    basePackage: com.xiongyc.product
    title: 产品服务
    description: 这是一个声明
    contact: YouCai.Xiong,www.baidu.com,764340703@qq.com
    version: 1.0
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  resources:
    static-locations:
    - classpath:static/
  application:
    name: product-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.107.87.255:3306/dika?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    port: 6379
    host: 47.107.87.255
    password: xiong5710565
logging:
  level:
    com.xiongyc.product: DEBUG
wx:
  token: token
  appId: wxbbf02c89c3eadd61
  appSecret: e5446349d5e000df0a8d9bbcc96978d5
  grantType: client_credential
sms:
  regionId: cn-hangzhou
  accessKeyId: LTAI4G9WTFC3xKc5b7YnvHc6
  secret: YEjtBzZAyWaHK6bS24h1aJluQ3jnpp
  domain: dysmsapi.aliyuncs.com
  version: 2017-05-25T00:00:00Z
  action: SendSms
HASOR_DATAQL_DATAWAY: true
HASOR_DATAQL_DATAWAY_ADMIN: true
HASOR_DATAQL_DATAWAY_API_URL: /api/
HASOR_DATAQL_DATAWAY_UI_URL: /interface-ui/
HASOR_DATAQL_FX_PAGE_DIALECT: mysql