server:
  port: 8080 
  servlet:
    context-path: /weChat

eureka:
  client:
    service-url:
#       defaultZone: http://admin:123456@120.24.75.28:9003/eureka/eureka
       defaultZone: http://admin:123456@59.110.216.184:9001/eureka,http://admin:123456@47.107.181.95:9002/eureka,http://admin:123456@120.24.75.28:9003/eureka
  instance:
    instance-id: product-service 
    prefer-ip-address: true

mybatis:
  type-aliases-package: com.xiongyc.product.bean
  mapper-locations: # 所有的mapper映射文件
  - classpath:mapper/*.xml 

api: 
  swagger: 
    basePackage: com.xiongyc.product
    title: 产品服务
    description: 这是一个声明
    contact: YouCai.Xiong,www.baidu.com,764340703@qq.com
    version: 1.0

spring: 
  thymeleaf:
    prefix: classpath:/templates/
  application: 
    name: product-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # 配置MySQL的驱动程序类
    url: jdbc:mysql://120.79.207.20:3306/fsylitcps?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT%2B8 # 数据库连接地址
    username: erp # 数据库用户名
    password: erp@fsfdad # 数据库连接密码   \
#    url: jdbc:mysql://172.1.10.24:3306/afterSale?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
#    username: root # 数据库用户名
#    password: 123456 # 数据库连接密码    
  redis: 
    port: 6379
    host: 47.107.158.20
    password: edo9567
  
logging:
  level:
    com.xiongyc.product: DEBUG #INFO
 